site_name: Documentación API GradienteSur | Cómputo general y modelos de IA
site_url: https://gradientesur.com/docs/
nav:
  - introducción: index.md
  - comenzando:
      - autenticación: comenzando/autenticacion.md
      - inicio rápido: comenzando/index.md
  - APIs:
      - resumen: apis.md
      - chat completions: apis/chat-completions.md
      - chat completions con imagen: apis/chat-completions-vision.md
      - audio transcriptions: apis/audio-transcriptions.md
      - audio speech: apis/audio-speech.md
      - embeddings: apis/embeddings.md
      - modelos disponibles: apis/models-endpoint.md
  - modelos: modelos.md
  - precios: pricings.md
  - changelog: changelog.md
theme:
  name: material
  language: es
  features:
    - navigation.footer
    - content.code.copy
  logo: gradiente.png
  favicon: gradiente.png
  palette:
    primary: indigo
    accent: indigo
extra_javascript:
  - js/dynamic-loader.js
markdown_extensions:
  - admonition
  - codehilite:
      use_pygments: true
      noclasses: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - gen-files:
      scripts:
        - scripts/gen_index.py